version: '2'

services:
  db:
    tty: true
    image: 'postgres'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      # - POSTGRES_HOST=f0f7ef18a660
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=testdb
      - POSTGRES_PASSWORD=secret

  myapp:
    tty: true
    image: bitnami/laravel:6-debian-9
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_DATABASE=testdb
      - DB_PASSWORD=secret
    depends_on:
      - db
    ports:
      - 5432:5432
    volumes:
      - ./:/app

  # appdb:
  #   image: postgres:11.6
  #   container_name: "appdb"
    # enviroment
    # privileged: true # Privileged mode could be required to run this container under Windows
